[[kalign]]
arch = "aarch64"
git-tree-sha1 = "37b4e538d4aa3e7936f173c42c438067ecaef4a4"
os = "macos"

    [[kalign.download]]
    sha256 = "c886b699abaedf0866fa7549395ebebe06ee057da1ba0d23133cd8eafc1e15a6"
    url = "https://github.com/JuliaBinaryWrappers/kalign_jll.jl/releases/download/kalign-v3.4.0+0/kalign.v3.4.0.aarch64-apple-darwin.tar.gz"
[[kalign]]
arch = "aarch64"
git-tree-sha1 = "c060024b84d9399c4cedc244c632bf155d5c7930"
libc = "glibc"
os = "linux"

    [[kalign.download]]
    sha256 = "46ff2d14c60a36435c55699e05741bde087a8b113263b98985968b5faac9bada"
    url = "https://github.com/JuliaBinaryWrappers/kalign_jll.jl/releases/download/kalign-v3.4.0+0/kalign.v3.4.0.aarch64-linux-gnu.tar.gz"
[[kalign]]
arch = "aarch64"
git-tree-sha1 = "ac7168275b9d548c68bf325862e421f47198c32a"
libc = "musl"
os = "linux"

    [[kalign.download]]
    sha256 = "0bc04a3dab1542aa2b50592d75b217b36fa52e5bdc4d81d02a437ccf1c52e897"
    url = "https://github.com/JuliaBinaryWrappers/kalign_jll.jl/releases/download/kalign-v3.4.0+0/kalign.v3.4.0.aarch64-linux-musl.tar.gz"
[[kalign]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8558046ab1237bc23f6c0184f69291ca1d8a8948"
libc = "glibc"
os = "linux"

    [[kalign.download]]
    sha256 = "7a64908eee3f948c572229169fae394840b958010601cfe4b084c13e38a60518"
    url = "https://github.com/JuliaBinaryWrappers/kalign_jll.jl/releases/download/kalign-v3.4.0+0/kalign.v3.4.0.armv6l-linux-gnueabihf.tar.gz"
[[kalign]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2d21d100647ff7c82811808bb6dab75709189df5"
libc = "musl"
os = "linux"

    [[kalign.download]]
    sha256 = "a394efd629a70e4b9eb67fcca51ef52611b351781f185ca4391ea734d88b74bf"
    url = "https://github.com/JuliaBinaryWrappers/kalign_jll.jl/releases/download/kalign-v3.4.0+0/kalign.v3.4.0.armv6l-linux-musleabihf.tar.gz"
[[kalign]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a0fb664c479c7df8d38877ff911df6c7ee7de31b"
libc = "glibc"
os = "linux"

    [[kalign.download]]
    sha256 = "fbba55f7f95cb3371ccc706ca2220ef7374e697de06795c42791b7fad53b2290"
    url = "https://github.com/JuliaBinaryWrappers/kalign_jll.jl/releases/download/kalign-v3.4.0+0/kalign.v3.4.0.armv7l-linux-gnueabihf.tar.gz"
[[kalign]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9352c6f485d65336a75d12546b6e45bee2c7110c"
libc = "musl"
os = "linux"

    [[kalign.download]]
    sha256 = "34ccd7c6cc4002b246f6ea1229fd428838f6dab531790af60a1ee5d64bbea8c8"
    url = "https://github.com/JuliaBinaryWrappers/kalign_jll.jl/releases/download/kalign-v3.4.0+0/kalign.v3.4.0.armv7l-linux-musleabihf.tar.gz"
[[kalign]]
arch = "i686"
git-tree-sha1 = "7f032dbc36ceb45cf3a3d18558b6b8370ca24553"
libc = "glibc"
os = "linux"

    [[kalign.download]]
    sha256 = "97c89c1228e558064404ee31b610e2ab628a9654b46f2a2f1af682f90b93810c"
    url = "https://github.com/JuliaBinaryWrappers/kalign_jll.jl/releases/download/kalign-v3.4.0+0/kalign.v3.4.0.i686-linux-gnu.tar.gz"
[[kalign]]
arch = "i686"
git-tree-sha1 = "82d070d3031fbd764c38959bcfb7a2cb8d771ba6"
libc = "musl"
os = "linux"

    [[kalign.download]]
    sha256 = "e79a63bd12418336af96415e828c7498239bfd1ca67d7dcde61e9207d9df0358"
    url = "https://github.com/JuliaBinaryWrappers/kalign_jll.jl/releases/download/kalign-v3.4.0+0/kalign.v3.4.0.i686-linux-musl.tar.gz"
[[kalign]]
arch = "powerpc64le"
git-tree-sha1 = "fb8fec9f75682b3b4ec8e1ca5598abc6360c1795"
libc = "glibc"
os = "linux"

    [[kalign.download]]
    sha256 = "21db566326d8130a6a83a3c85ae1278d27a1e712261b899d989914edfc632d91"
    url = "https://github.com/JuliaBinaryWrappers/kalign_jll.jl/releases/download/kalign-v3.4.0+0/kalign.v3.4.0.powerpc64le-linux-gnu.tar.gz"
[[kalign]]
arch = "x86_64"
git-tree-sha1 = "63f1e83f9f9647ecb88ad241c4c29e77d51d60e6"
os = "macos"

    [[kalign.download]]
    sha256 = "5e96c940921519ba9a3fbf087cece36bd8a9f8575c5970959d1282b97a58eb32"
    url = "https://github.com/JuliaBinaryWrappers/kalign_jll.jl/releases/download/kalign-v3.4.0+0/kalign.v3.4.0.x86_64-apple-darwin.tar.gz"
[[kalign]]
arch = "x86_64"
git-tree-sha1 = "e792c934a99731bd7067e6bc9c4c3ddbdb5806fe"
libc = "glibc"
os = "linux"

    [[kalign.download]]
    sha256 = "23e020268f8e4ce59874696475e5737f8c2d245658ea6c59998707dc65ccd377"
    url = "https://github.com/JuliaBinaryWrappers/kalign_jll.jl/releases/download/kalign-v3.4.0+0/kalign.v3.4.0.x86_64-linux-gnu.tar.gz"
[[kalign]]
arch = "x86_64"
git-tree-sha1 = "f091f3b4cb0ce8c55f76bb907b05a613b115b054"
libc = "musl"
os = "linux"

    [[kalign.download]]
    sha256 = "541506e1460a6ee0764c7199ed8a6041ebcc4d82e70dab9024b6aae969fb4d77"
    url = "https://github.com/JuliaBinaryWrappers/kalign_jll.jl/releases/download/kalign-v3.4.0+0/kalign.v3.4.0.x86_64-linux-musl.tar.gz"
[[kalign]]
arch = "x86_64"
git-tree-sha1 = "a934137e792057e69815c09afe4a1b4e4ac85c6c"
os = "freebsd"

    [[kalign.download]]
    sha256 = "a6a56cb311831783e556075381a88d4a3a5306f98ee53ef5f8920309c5a403e5"
    url = "https://github.com/JuliaBinaryWrappers/kalign_jll.jl/releases/download/kalign-v3.4.0+0/kalign.v3.4.0.x86_64-unknown-freebsd.tar.gz"
