# Autogenerated wrapper script for kalign_jll for x86_64-apple-darwin
export kalign, libkalign

using LLVMOpenMP_jll
JLLWrappers.@generate_wrapper_header("kalign")
JLLWrappers.@declare_library_product(libkalign, "@rpath/libkalign.3.dylib")
JLLWrappers.@declare_executable_product(kalign)
function __init__()
    JLLWrappers.@generate_init_header(LLVMOpenMP_jll)
    JLLWrappers.@init_library_product(
        libkalign,
        "lib/libkalign.3.4.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        kalign,
        "bin/kalign",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
